version: '3.7'

services:

  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.8.0
    restart: on-failure:6
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  # 9092 port is for external access
  # 9094 port is for internal access
  broker-1:
    container_name: broker
    image: confluentinc/cp-kafka:7.2.1
    restart: on-failure:6
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-1:9094,OUTSIDE://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101

  schema-registry:
    container_name: schema-registry
    hostname: schema-registry
    image: confluentinc/cp-schema-registry:7.2.1
    restart: on-failure:6
    depends_on:
      - broker-1
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "broker-1:9094"

  akhq:
    container_name: akhq
    image: tchiotludo/akhq:0.21.0
    restart: on-failure:6
    ports:
      - "8087:8080"
    links:
      - broker-1
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "broker-1:9094"
              schema-registry:
                url: "http://schema-registry:8081"
              connect:
                - name: connect-1
                  url: "http://debezium-connect:8083"


volumes:
  pgdata:
